name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 3 * * *" # a cada 2 dias (03:00 UTC)
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Update heartbeat
        run: |
          PGPASSWORD=${{ secrets.DB_PASSWORD }} \
          psql \
            -h ${{ secrets.DB_HOST }} \
            -p ${{ secrets.DB_PORT }} \
            -U ${{ secrets.DB_USER }} \
            -d ${{ secrets.DB_NAME }} \
            -c "UPDATE heartbeat SET last_ping = NOW() WHERE id = 1;"
